inherit_gem:
  gnar-style:
    - "rubocop/rubocop_rails.yml"

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120
  Severity: refactor

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 15
  ExcludedMethods:
    - json

Metrics/ParameterLists:
  CountKeywordArgs: false
