version: '3'
services:
  db:
    image: postgres
    ports:
      - 5434:5432
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tmp/nginx:/var/cache/nginx
    ports:
      - 3001:3001
    links:
      - app
  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@db
    links:
      - db
