default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: dts_development

test:
  <<: *default
  database: dts_test

production:
  <<: *default
  database: dts_production
  username: dts
  password: <%= ENV['DTS_DATABASE_PASSWORD'] %>
